name: Deploy to ECS

on:
  push:
    branches:
      - feature/practice

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up AWS credentials and region
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV



    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

 
    - name: Update ECS task definition
      run: |
        FAMILY=${{ secrets.ECS_TASK_DEFINITION }}
        IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
  
    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ secrets.ECS_SERVICE_NAME }} \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
          --force-new-deployment

